""" dotstribute operations

Operations:
    generate_dotignore
    get_files
    link
    preview
"""

import os


def get_files(git_path, home_path, dotignore_file=".dotignore"):
    # types: (str, str, str) -> Dict[str,str]
    """ Generate the path of files in your dotfile directory.

    These paths will include both full paths to your $HOME directory
    and full paths to your dot directory.
    """

    def _get_ignore_files(ignore_filename='.dotignore'):
        # types: (str) -> List[str]
        """ Get list of files to be ignored based on dotignore file """

        ignore_files = []
        if os.path.exists(ignore_filename):
            with open(ignore_filename) as ignore_file:
                ignore_files = [i.strip() for i in ignore_file.readlines()]

        return ignore_files + [os.path.basename(ignore_filename)]


    symlinks = {}

    dotignore_file = os.path.join(git_path, dotignore_file)
    ignore_files = _get_ignore_files(dotignore_file)

    for filename in os.listdir(git_path):
        if filename in ignore_files:
            continue

        sym_from = os.path.join(os.path.abspath(git_path), filename)

        # prepend a dot if the files do not start with one
        if not filename.startswith("."):
            filename = '.' + filename

        symlinks[sym_from] = os.path.join(home_path, filename)

    # git paths, home paths
    return symlinks


'''
def link(self, ask=False):
    """
    Link files, generated by get_files(), to your home directory.

    Run get_files() first.
    """

    for i, f in enumerate(self.git_links):

        # make sure to ask nicely
        if ask and not os.path.exists(self.home_links[i]):
            if raw_input("Link %s to home (y/N)? > " % f).lower() == "y":
                os.symlink(f, self.home_links[i])

        # don't ask, just do
        elif not os.path.exists(self.home_links[i]):
            os.symlink(f, self.home_links[i])

        else:
            print "skipping", f

def unlink(self, ask=False):
    """
    Delete the links made in your home directory based on the
    contents of your dotfile directory.

    Run get_files() first.
    """
    for f in self.home_links:

        # ask to delete
        if ask and os.path.exists(f):
            if raw_input("Unlink %s (y/N)? > " % f).lower() == "y":
                os.unlink(f)

        # don't ask, just do
        elif os.path.exists(f):
            os.unlink(f)

        else:
            print "Does not exist:", f

def preview(unlink_preview=False):
    """
    Preview the changes to be made before executing them.

    Run get_files() first.
    """

    for i, f in enumerate(self.home_links):
        if unlink_preview:
            print "* UNLINK %s \n\t<- %s" %(f, self.git_links[i])

        else:
            print "* LINK: %s \n\t-> %s" %(self.git_links[i], f)

'''
def generate_dotignore(to_path, overwrite=False):
    # types: (str, bool) -> None
    """ Generate a .dotignore file at the specified location

    defaults typically found in a git directory:
        .git
        .gitignore
        README.md
        LICENSE
    """

    to_dir = os.path.join(os.path.abspath(to_dir), '.dotignore')

    if not overwrite and os.path.exists(to_dir):
        print('.dotignore file already exists in {}'.format(to_dir))
        return

    # generic files you might find in a git directory
    defaults = [
        '.git',
        '.gitignore',
        'README.md',
        'LICENSE',
    ]
    ignore_files = '\n'.join(defaults)
    with open(to_dir, 'w') as f:
        f.write(ignore_files)
